//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class SliderrMetaData
    {
        [Key]
        public int SliderID { get; set; }
        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "لطفا را {0} وارد کنید")]
        public string Title { get; set; }
        [Display(Name = "سرنویس")]
        [Required(ErrorMessage = "لطفا را {0} وارد کنید")]
        [Url(ErrorMessage = "آدرس وارد شده معتبر نمیباشد")]
        public string Url { get; set; }
        [Display(Name = "تصویر")]
        public string ImageName { get; set; }
        [Display(Name = "از هنگام")]
        [DisplayFormat(DataFormatString = "{0:yyyy/mm/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime StartDate { get; set; }
        [Display(Name = "تا هنگام")]
        [DisplayFormat(DataFormatString = "{0:yyyy/mm/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime EndDate { get; set; }
        [Display(Name = "وضعیت")]
        public bool IsActive { get; set; }
    }
}